project_id = "iwgbcneinoojcvcsixib"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.sync-user-to-sheets]
verify_jwt = false
